default['airbitz']['app']['user'] = "vagrant"
default['airbitz']['app']['group'] = "vagrant"
default['airbitz']['app']['home'] = "/home/vagrant"
default['airbitz']['database']['name'] = "airbitz"
default['airbitz']['database']['username'] = "styx"
default['airbitz']['database']['password'] = "styx"
