
Vagrant.configure("2") do |config|
  config.omnibus.chef_version = '11.10'
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.network :forwarded_port, guest: 8000, host: 1224
  config.vm.network :forwarded_port, guest: 80, host: 8888
  config.vm.network :forwarded_port, guest: 8983, host: 8983
  config.vm.provision :shell, :inline => "sudo apt-get update"
  config.vm.synced_folder "../airbitz", "/airbitz", :create => true
  config.vm.synced_folder "../staging", "/staging", :create => true

  config.vm.provider :digital_ocean do |provider, override|
    override.ssh.private_key_path = '~/.ssh/id_rsa'
    override.vm.box = 'digital_ocean'
    override.vm.box_url = "https://github.com/smdahlen/vagrant-digitalocean/raw/master/box/digital_ocean.box"

    provider.image = "Ubuntu 12.04.3 x64"
    provider.client_id = ENV['DIGITAL_OCEAN_CLIENT_ID']
    provider.api_key = ENV['DIGITAL_OCEAN_API_KEY']
  end

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "../chef/cookbooks/"
    chef.add_recipe "airbitz::web"
    chef.add_recipe "airbitz::db"
    chef.add_recipe "airbitz::search"
    chef.json = {
      :airbitz => {
        :app => {
          :user => "vagrant",
          :group => "vagrant",
          :home => "/home/vagrant"
        },
        :database => {
          :name => 'airbitz_directory',
          :username => "airbitz",
          :password => "airbitz"
        }
      },
    }
  end
end

# -*- mode: ruby -*-
# vi: set ft=ruby :

