# used in template context processor 'active_regions'
def get_active_regions_list(region):
    regions = list()

    if region == 'SOUTHAMERICA':
        for region_code, data in ACTIVE_REGIONS_SOUTH_AMERICA.items():
            if '-' not in region_code:
                regions.append((data['name'], data['search']))
    elif region == 'ASIA':
        for region_code, data in ACTIVE_REGIONS_ASIA.items():
            if '-' not in region_code:
                regions.append((data['name'], data['search']))
    elif region == 'SOUTHEAST_ASIA':
        for region_code, data in ACTIVE_REGIONS_SOUTHEAST_ASIA.items():
            if '-' not in region_code:
                regions.append((data['name'], data['search']))
    elif region == 'EUROPE':
        for region_code, data in ACTIVE_REGIONS_EUROPE.items():
            if '-' not in region_code:
                regions.append((data['name'], data['search']))
    elif region == 'OCEANA':
        for region_code, data in ACTIVE_REGIONS_OCEANA.items():
            if '-' not in region_code:
                regions.append((data['name'], data['search']))
    else:
        for region_code, data in ACTIVE_REGIONS.items():
            if region in region_code:
                regions.append((data['name'], data['search']))

    regions.sort(key=lambda data: data[0])

    return regions


# ISO_3166 Region codes http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
# these correspond to jvectormaps

US_REGIONS = {
    'US-CA': {'name': 'California',
              'search': 'California, United States'},
    'US-TX': {'name': 'Texas',
              'search': 'Texas, United States'},
    'US-NY': {'name': 'New York',
              'search': 'New York, United States'},
    'US-HI': {'name': 'Hawaii',
              'search': 'Hawaii, United States'},
    'US-NJ': {'name': 'New Jersey',
              'search': 'New Jersey, United States'},
    'US-GA': {'name': 'Georgia',
              'search': 'Georgia, United States'},
    'US-IL': {'name': 'Illinois',
              'search': 'Illinois, United States'},
    'US-UT': {'name': 'Utah',
              'search': 'Utah, United States'},
    'US-NV': {'name': 'Nevada',
              'search': 'Nevada, United States'},
    'US-CO': {'name': 'Colorado',
              'search': 'Colorado, United States'},
    'US-FL': {'name': 'Florida',
              'search': 'Florida, United States'},
    'US-NH': {'name': 'New Hampshire',
              'search': 'New Hapshire, United States'},
    'US-MA': {'name': 'Massachusetts',
              'search': 'Massachusetts, United States'},
    'US-VT': {'name': 'Vermont',
              'search': 'Vermont, United States'},
    'US-PA': {'name': 'Pennsylvania',
              'search': 'Pennsylvania, United States'},
    'US-CT': {'name': 'Connecticut',
              'search': 'Connecticut, United States'},
    'US-DE': {'name': 'Delaware',
              'search': 'Delaware, United States'},
    'US-MD': {'name': 'Maryland',
              'search': 'Maryland, United States'},
    'US-ME': {'name': 'Maine',
              'search': 'Maine, United States'},
    'US-WA': {'name': 'Washington',
              'search': 'Washington, United States'},
    'US-OR': {'name': 'Oregon',
              'search': 'Oregon, United States'},
    'US-AK': {'name': 'Alaska',
              'search': 'Alaska, United States'},
    'US-AZ': {'name': 'Arizona',
              'search': 'Arizona, United States'},
    'US-NM': {'name': 'New Mexico',
              'search': 'New Mexico, United States'},
    'US-MI': {'name': 'Michigan',
              'search': 'Michigan, United States'},
    'US-MN': {'name': 'Minnesota',
              'search': 'Minnesota, United States'},
    'US-DC': {'name': 'Washington DC',
              'search': 'Washington, DC, United States'},
    'US-IN': {'name': 'Indiana',
              'search': 'Indiana, United States'},
    'US-IA': {'name': 'Iowa',
              'search': 'Iowa, United States'},
    'US-KS': {'name': 'Kansas',
              'search': 'Kansas, United States'},
    'US-WY': {'name': 'Wyoming',
              'search': 'Wyoming, United States'},
    'US-MT': {'name': 'Montana',
              'search': 'Montana, United States'},
    'US-ID': {'name': 'Idaho',
              'search': 'Idaho, United States'},
    'US-ND': {'name': 'North Dakota',
              'search': 'North Dakota, United States'},
    'US-SD': {'name': 'South Dakota',
              'search': 'South Dakota, United States'},
    'US-NE': {'name': 'Nebraska',
              'search': 'Nebraska, United States'},
    'US-MO': {'name': 'Missouri',
              'search': 'Missouri, United States'},
    'US-OK': {'name': 'Oklahoma',
              'search': 'Oklahoma, United States'},
    'US-AR': {'name': 'Arkansas',
              'search': 'Arkansas, United States'},
    'US-LA': {'name': 'Louisiana',
              'search': 'Louisiana, United States'},
    'US-MS': {'name': 'Mississippi',
              'search': 'Mississippi, United States'},
    'US-AL': {'name': 'Alabama',
              'search': 'Alabama, United States'},
    'US-TN': {'name': 'Tennessee',
              'search': 'Tennessee, United States'},
    'US-KY': {'name': 'Kentucky',
              'search': 'Kentucky, United States'},
    'US-OH': {'name': 'Ohio',
              'search': 'Ohio, United States'},
    'US-WV': {'name': 'West Virginia',
              'search': 'West Virginia, United States'},
    'US-VA': {'name': 'Virginia',
              'search': 'Virginia, United States'},
    'US-NC': {'name': 'North Carolina',
              'search': 'North Carolina, United States'},
    'US-SC': {'name': 'South Carolina',
              'search': 'South Carolina, United States'},
    'US-WI': {'name': 'Wisconsin',
              'search': 'Wisconsin, United States'},
    'US-RI': {'name': 'Rhode Island',
              'search': 'Rhode Island, United States'},
}

CA_REGIONS = {
    'CA-ON': {'name': 'Ontario',
              'search': 'Ontario, Canada'},
    'CA-BC': {'name': 'British Columbia',
              'search': 'Ontario, Canada'},
    'CA-QC': {'name': 'Quebec',
              'search': 'Quebec, Canada'},
    'CA-YT': {'name': 'Yukon',
              'search': 'Yukon, Canada'},
    'CA-NT': {'name': 'Northwest Territories',
              'search': 'Northwest Territories, Canada'},
    'CA-NU': {'name': 'Nunavut',
              'search': 'Nunavut, Canada'},
    'CA-AB': {'name': 'Alberta',
              'search': 'Alberta, Canada'},
    'CA-SK': {'name': 'Saskatchewan',
              'search': 'Saskatchewan, Canada'},
    'CA-MB': {'name': 'Manitoba',
              'search': 'Manitoba, Canada'},
    'CA-NL': {'name': 'Newfoundland and Labrador',
              'search': 'Newfoundland and Labrador, Canada'},
    'CA-NB': {'name': 'New Brunswick',
              'search': 'New Brunswick, Canada'},
    'CA-NS': {'name': 'Nova Scotia',
              'search': 'Nova Scotia, Canada'},
    'CA-PE': {'name': 'Prince Edward Island',
              'search': 'Prince Edward Island, Canada'},
}

EU_REGIONS = {
    'NL': {'name': 'Netherlands',
           'search': 'Netherlands'},
    'IS': {'name': 'Iceland',
       'search': 'Iceland'},
    'GB': {'name': 'United Kingdom',
       'search': 'United Kingdom'},
    'IE': {'name': 'Ireland',
       'search': 'Ireland'},
    'NO': {'name': 'Norway',
       'search': 'Norway'},
    'SE': {'name': 'Sweden',
       'search': 'Sweden'},
    'FI': {'name': 'Finland',
       'search': 'Finland'},
    'RU': {'name': 'Russia',
       'search': 'Russia'},
    'EE': {'name': 'Estonia',
       'search': 'Estonia'},
    'LV': {'name': 'Latvia',
       'search': 'Latvia'},
    'BY': {'name': 'Belarus',
       'search': 'Belarus'},
    'UA': {'name': 'Ukraine',
       'search': 'Ukraine'},
    'LT': {'name': 'Lithuania',
       'search': 'Lithuania'},
    'MD': {'name': 'Moldova',
       'search': 'Moldova'},
    'RO': {'name': 'Romania',
       'search': 'Romania'},
    'BG': {'name': 'Bulgaria',
       'search': 'Bulgaria'},
    'TR': {'name': 'Turkey',
       'search': 'Turkey'},
    'GR': {'name': 'Greece',
       'search': 'Greece'},
    'AL': {'name': 'Albania',
       'search': 'Albania'},
    'MK': {'name': 'Macedonia',
       'search': 'Macedonia'},
    'RS': {'name': 'Republic of Serbia',
       'search': 'Republic of Serbia'},
    'SK': {'name': 'Slovakia',
       'search': 'Slovakia'},
    'PL': {'name': 'Poland',
       'search': 'Poland'},
    'DE': {'name': 'Germany',
       'search': 'Germany'},
    'CZ': {'name': 'Czech Republic',
       'search': 'Czech Republic'},
    'AT': {'name': 'Austria',
       'search': 'Austria'},
    'HR': {'name': 'Croatia',
       'search': 'Croatia'},
    'BA': {'name': 'Bosnia and Herzegovina',
       'search': 'Bosnia and Herzegovina'},
    'ME': {'name': 'Montenegro',
       'search': 'Montenegro'},
    'BE': {'name': 'Belgium',
       'search': 'Belgium'},
    'FR': {'name': 'France',
       'search': 'France'},
    'IT': {'name': 'Italy',
       'search': 'Italy'},
    'CH': {'name': 'Switzerland',
       'search': 'Switzerland'},
    'ES': {'name': 'Spain',
       'search': 'Spain'},
    'PT': {'name': 'Portugal',
       'search': 'Portugal'},
    'SY': {'name': 'Syria',
       'search': 'Syria'},
    'IQ': {'name': 'Iraq',
       'search': 'Iraq'},
    'LB': {'name': 'Lebanon',
       'search': 'Lebanon'},
    'IL': {'name': 'Israel',
       'search': 'Israel'},
    'JO': {'name': 'Jordan',
       'search': 'Jordan'},
    'SA': {'name': 'Saudi Arabia',
       'search': 'Saudi Arabia'},
    'EG': {'name': 'Egypt',
       'search': 'Egypt'},
    'LY': {'name': 'Libya',
       'search': 'Libya'},
    'DZ': {'name': 'Algeria',
       'search': 'Algeria'},
    'TN': {'name': 'Tanzania',
       'search': 'Tanzania'},
    'MA': {'name': 'Morocco',
       'search': 'Morocco'},
    'PS': {'name': 'West Bank',
       'search': 'West Bank'},
    'SI': {'name': 'Slovenia',
       'search': 'Slovenia'},
    '2': {'name': 'Kosovo',
       'search': 'Kosovo'},
    'LU': {'name': 'Luxembourg',
       'search': 'Luxembourg'},
    'LI': {'name': 'Liechenstein',
       'search': 'Liechenstein'},
}

SOUTH_AMERICA_REGIONS = {}  # TODO: get full list

ASIA_REGIONS = {}           # TODO: get full list

# Regions listed with partial coverage listed below
ACTIVE_REGIONS_EUROPE = {
    # EU regions
    'NL': {'name': 'Netherlands',
           'search': 'Netherlands'},
    'GB': {'name': 'United Kingdom',
           'search': 'United Kingdom'},
    'DE': {'name': 'Germany',
           'search': 'Germany'},
    'AT': {'name': 'Austria',
           'search': 'Austria'},
    'IE': {'name': 'Ireland',
           'search': 'Ireland'},

}

ACTIVE_REGIONS_SOUTH_AMERICA = {
    # South American regions
    'BR': {'name': 'Brazil',
           'search': 'Brazil'},
    'AR': {'name': 'Argentina',
           'search': 'Argentina'},
}

ACTIVE_REGIONS_ASIA = {
    # Asian regions
    'HK': {'name': 'Hong Kong',
           'search': 'Hong Kong'},
}

ACTIVE_REGIONS_SOUTHEAST_ASIA = {
    # Southeast Asian regions
    'PH': {'name': 'Philippines',
           'search': 'Philippines'},
}

ACTIVE_REGIONS_OCEANA = {
    # Oceana regions
    'AU': {'name': 'Austrailia',
           'search': 'Austrailia'},
    'NZ': {'name': 'New Zealand',
           'search': 'New Zealand'},
}

ACTIVE_REGIONS = {}
ACTIVE_REGIONS.update(US_REGIONS)   # all
ACTIVE_REGIONS.update(CA_REGIONS)   # all
ACTIVE_REGIONS.update(ACTIVE_REGIONS_EUROPE)            # partial
ACTIVE_REGIONS.update(ACTIVE_REGIONS_ASIA)              # partial
ACTIVE_REGIONS.update(ACTIVE_REGIONS_SOUTHEAST_ASIA)    # partial
ACTIVE_REGIONS.update(ACTIVE_REGIONS_SOUTH_AMERICA)     # partial
ACTIVE_REGIONS.update(ACTIVE_REGIONS_OCEANA)        # partial

# ALL_REGIONS = dict(US_REGIONS.items() + CA_REGIONS.items() + EU_REGIONS.items())
ALL_REGIONS = {}
ALL_REGIONS.update(US_REGIONS)
ALL_REGIONS.update(CA_REGIONS)
ALL_REGIONS.update(EU_REGIONS)








ALL_COUNTRIES = {
    "AD": "Andorra",
    "AE": "United Arab Emirates",
    "AF": "Afghanistan",
    "AG": "Antigua and Barbuda",
    "AI": "Anguilla",
    "AL": "Albania",
    "AM": "Armenia",
    "AO": "Angola",
    "AQ": "Antarctica",
    "AR": "Argentina",
    "AS": "American Samoa",
    "AT": "Austria",
    "AU": "Australia",
    "AW": "Aruba",
    "AX": "Aland Islands",
    "AZ": "Azerbaijan",
    "BA": "Bosnia and Herzegovina",
    "BB": "Barbados",
    "BD": "Bangladesh",
    "BE": "Belgium",
    "BF": "Burkina Faso",
    "BG": "Bulgaria",
    "BH": "Bahrain",
    "BI": "Burundi",
    "BJ": "Benin",
    "BL": "Saint Barthelemy",
    "BM": "Bermuda",
    "BN": "Brunei Darussalam",
    "BO": "Bolivia, Plurinational State of",
    "BQ": "Bonaire, Sint Eustatius and Saba",
    "BR": "Brazil",
    "BS": "Bahamas",
    "BT": "Bhutan",
    "BV": "Bouvet Island",
    "BW": "Botswana",
    "BY": "Belarus",
    "BZ": "Belize",
    "CA": "Canada",
    "CC": "Cocos (Keeling) Islands",
    "CD": "Congo, the Democratic Republic of the",
    "CF": "Central African Republic",
    "CG": "Congo",
    "CH": "Switzerland",
    "CI": "Cote d'Ivoire",
    "CK": "Cook Islands",
    "CL": "Chile",
    "CM": "Cameroon",
    "CN": "China",
    "CO": "Colombia",
    "CR": "Costa Rica",
    "CU": "Cuba",
    "CV": "Cabo Verde",
    "CW": "Curacao",
    "CX": "Christmas Island",
    "CY": "Cyprus",
    "CZ": "Czech Republic",
    "DE": "Germany",
    "DJ": "Djibouti",
    "DK": "Denmark",
    "DM": "Dominica",
    "DO": "Dominican Republic",
    "DZ": "Algeria",
    "EC": "Ecuador",
    "EE": "Estonia",
    "EG": "Egypt",
    "EH": "Western Sahara",
    "ER": "Eritrea",
    "ES": "Spain",
    "ET": "Ethiopia",
    "FI": "Finland",
    "FJ": "Fiji",
    "FK": "Falkland Islands (Malvinas)",
    "FM": "Micronesia, Federated States of",
    "FO": "Faroe Islands",
    "FR": "France",
    "GA": "Gabon",
    "GB": "United Kingdom",
    "GD": "Grenada",
    "GE": "Georgia",
    "GF": "French Guiana",
    "GG": "Guernsey",
    "GH": "Ghana",
    "GI": "Gibraltar",
    "GL": "Greenland",
    "GM": "Gambia",
    "GN": "Guinea",
    "GP": "Guadeloupe",
    "GQ": "Equatorial Guinea",
    "GR": "Greece",
    "GS": "South Georgia and the South Sandwich Islands",
    "GT": "Guatemala",
    "GU": "Guam",
    "GW": "Guinea-Bissau",
    "GY": "Guyana",
    "HK": "Hong Kong",
    "HM": "Heard Island and McDonald Islands",
    "HN": "Honduras",
    "HR": "Croatia",
    "HT": "Haiti",
    "HU": "Hungary",
    "ID": "Indonesia",
    "IE": "Ireland",
    "IL": "Israel",
    "IM": "Isle of Man",
    "IN": "India",
    "IO": "British Indian Ocean Territory",
    "IQ": "Iraq",
    "IR": "Iran, Islamic Republic of",
    "IS": "Iceland",
    "IT": "Italy",
    "JE": "Jersey",
    "JM": "Jamaica",
    "JO": "Jordan",
    "JP": "Japan",
    "KE": "Kenya",
    "KG": "Kyrgyzstan",
    "KH": "Cambodia",
    "KI": "Kiribati",
    "KM": "Comoros",
    "KN": "Saint Kitts and Nevis",
    "KP": "Korea, Democratic People's Republic of",
    "KR": "Korea, Republic of",
    "KW": "Kuwait",
    "KY": "Cayman Islands",
    "KZ": "Kazakhstan",
    "LA": "Lao People's Democratic Republic",
    "LB": "Lebanon",
    "LC": "Saint Lucia",
    "LI": "Liechtenstein",
    "LK": "Sri Lanka",
    "LR": "Liberia",
    "LS": "Lesotho",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "LV": "Latvia",
    "LY": "Libya",
    "MA": "Morocco",
    "MC": "Monaco",
    "MD": "Moldova, Republic of",
    "ME": "Montenegro",
    "MF": "Saint Martin (French part)",
    "MG": "Madagascar",
    "MH": "Marshall Islands",
    "MK": "Macedonia, the former Yugoslav Republic of",
    "ML": "Mali",
    "MM": "Myanmar",
    "MN": "Mongolia",
    "MO": "Macao",
    "MP": "Northern Mariana Islands",
    "MQ": "Martinique",
    "MR": "Mauritania",
    "MS": "Montserrat",
    "MT": "Malta",
    "MU": "Mauritius",
    "MV": "Maldives",
    "MW": "Malawi",
    "MX": "Mexico",
    "MY": "Malaysia",
    "MZ": "Mozambique",
    "NA": "Namibia",
    "NC": "New Caledonia",
    "NE": "Niger",
    "NF": "Norfolk Island",
    "NG": "Nigeria",
    "NI": "Nicaragua",
    "NL": "Netherlands",
    "NO": "Norway",
    "NP": "Nepal",
    "NR": "Nauru",
    "NU": "Niue",
    "NZ": "New Zealand",
    "OM": "Oman",
    "PA": "Panama",
    "PE": "Peru",
    "PF": "French Polynesia",
    "PG": "Papua New Guinea",
    "PH": "Philippines",
    "PK": "Pakistan",
    "PL": "Poland",
    "PM": "Saint Pierre and Miquelon",
    "PN": "Pitcairn",
    "PR": "Puerto Rico",
    "PS": "Palestine, State of",
    "PT": "Portugal",
    "PW": "Palau",
    "PY": "Paraguay",
    "QA": "Qatar",
    "RE": "Reunion",
    "RO": "Romania",
    "RS": "Serbia",
    "RU": "Russian Federation",
    "RW": "Rwanda",
    "SA": "Saudi Arabia",
    "SB": "Solomon Islands",
    "SC": "Seychelles",
    "SD": "Sudan",
    "SE": "Sweden",
    "SG": "Singapore",
    "SH": "Saint Helena, Ascension and Tristan da Cunha",
    "SI": "Slovenia",
    "SJ": "Svalbard and Jan Mayen",
    "SK": "Slovakia",
    "SL": "Sierra Leone",
    "SM": "San Marino",
    "SN": "Senegal",
    "SO": "Somalia",
    "SR": "Suriname",
    "SS": "South Sudan",
    "ST": "Sao Tome and Principe",
    "SV": "El Salvador",
    "SX": "Sint Maarten (Dutch part)",
    "SY": "Syrian Arab Republic",
    "SZ": "Swaziland",
    "TC": "Turks and Caicos Islands",
    "TD": "Chad",
    "TF": "French Southern Territories",
    "TG": "Togo",
    "TH": "Thailand",
    "TJ": "Tajikistan",
    "TK": "Tokelau",
    "TL": "Timor-Leste",
    "TM": "Turkmenistan",
    "TN": "Tunisia",
    "TO": "Tonga",
    "TR": "Turkey",
    "TT": "Trinidad and Tobago",
    "TV": "Tuvalu",
    "TW": "Taiwan, Province of China",
    "TZ": "Tanzania, United Republic of",
    "UA": "Ukraine",
    "UG": "Uganda",
    "UM": "United States Minor Outlying Islands",
    "US": "United States",
    "UY": "Uruguay",
    "UZ": "Uzbekistan",
    "VA": "Holy See (Vatican City State)",
    "VC": "Saint Vincent and the Grenadines",
    "VE": "Venezuela, Bolivarian Republic of",
    "VG": "Virgin Islands, British",
    "VI": "Virgin Islands, U.S.",
    "VN": "Viet Nam",
    "VU": "Vanuatu",
    "WF": "Wallis and Futuna",
    "WS": "Samoa",
    "YE": "Yemen",
    "YT": "Mayotte",
    "ZA": "South Africa",
    "ZM": "Zambia",
    "ZW": "Zimbabwe"
}
